<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-04-20 at 17:35:27.
 */
class SuccessUITest extends PHPUnit_Framework_TestCase {

    /**
     * @var SuccessUI
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SuccessUI;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
