<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-04-20 at 17:35:16.
 */
class UniversalConnectTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UniversalConnect
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UniversalConnect;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers UniversalConnect::doConnect
     * @todo   Implement testDoConnect().
     */
    public function testDoConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
